removed mode system

diff --git a/src/bat b/src/bat
--- a/src/bat
+++ b/src/bat
@@ -1,17 +1,16 @@
 #/bin/bash
 
-# This script takes a mode, a test file, and (optionally)
+# This script takes a shell, a test file, and (optionally)
 # a delay as parameters and runs the test files in the
-# given mode with the delay between commands.
+# given shell with the delay between commands.
 #
 # usage:
-# cs100-runtests mode testFile[s] [delay]
+# cs100-runtests shell testFile[s] [delay]
 #
 #
-# mode: can be "rshell", "bash", or the path to an
-#    executable. rshell mode runs "bin/rshell". bash
-#    mode runs "bash -i". Any executable passed in
-#    is invoked verbatim
+# shell: can be programs like "bin/rshell" or "bash".
+#    bash gets run in interactive mode, and every
+#    other option is invoked verbatim.
 # 
 # testFile[s]: the file containing the tests. The name
 #    undergoes filename expansion
@@ -25,8 +24,7 @@
 #   * prints the name of the file currently being tested
 #     surrounded in stars
 #   * prints 80 '=' characters denoting start of tests
-#   * runs the program specified by mode, adjusting as
-#     needed.
+#   * runs the shell with the specified tests
 #   * prints 80 '=' characters denoting end of test
 #
 
@@ -46,9 +44,7 @@ red() {
 # prints usage to stderr then quits
 usage() {
   cat >&2 <<EOF
-Usage: $(basename $0) mode testFile[s] [delay]
-mode should be one of "rshell", "bash", or the path
-to an executable
+Usage: $(basename $0) shell testFile[s] [delay]
 EOF
   exit 1
 }
@@ -101,9 +97,9 @@ yieldLines() {
     fi
 
 
-    # if not in bash mode, print the current line to the screen
+    # if not using bash, print the current line to the screen
     # prints to fd 1 of the current process
-    if [[ "$MODE" != "bash" ]]
+    if [[ "$COMMAND_SHELL" != "bash" ]]
     then
       echo "${line}" >/proc/$CUR_PID/fd/1
     fi
@@ -119,8 +115,8 @@ yieldLines() {
 
 
 
-# first arguments is mode
-MODE=${1}
+# first arguments is command shell
+COMMAND_SHELL=${1}
 # second argument is for testfiles
 TEST_CASE_FILES=${2}
 # third argument is delay
@@ -148,25 +144,14 @@ fi
 
 
 
-# test if $1 is a valid mode (rshell, bash, or executable)
+# test if $1 is a valid executable (rshell, bash, or executable)
 # (see http://mywiki.wooledge.org/BashGuide/Practices#Bash_Tests)
-# the opposite of mode being rshell or bash or executable is
-# mode not being rshell and not being bash and not executable
-if [[ "$MODE" != "rshell" && "$MODE" != "bash" && ! -x "$MODE" ]]
-then
+command -v $COMMAND_SHELL || {
   red "Error: "
-  echo "improper mode" >&2
+  echo "\"$COMMAND_SHELL\" cannot be executed" >&2
   usage
-fi
+}
 
-# If mode is rshell, make sure bin/rshell exists and can be
-# executed
-if [[ "$MODE" == "rshell" && ! -x bin/rshell ]]
-then
-  red "Error: "
-  echo "bin/rshell cannot be executed" >&2
-  usage
-fi
 
 # Use regular expressions to make sure the delay is only made up of numbers
 # (see http://stackoverflow.com/questions/304864/how-do-i-use-regular-expressions-in-bash-scripts)
@@ -189,7 +174,7 @@ do
   # if the current file is a directory, recurse on it
   if [[ -d $file ]]
   then
-    $0 $MODE $file/ $U_DELAY
+    $0 $COMMAND_SHELL $file/ $U_DELAY
     # skip this iteration. No need to print for the directory
     continue
   elif [[ "$file" =~ ^.*/\*$ ]]
@@ -224,14 +209,11 @@ do
 
   # pipe output of yieldlines into a shell
   # (see http://www.tldp.org/LDP/abs/html/io-redirection.html)
-  if [[ "$MODE" == "rshell" ]]
+  if [[ "$COMMAND_SHELL" == "bash" ]]
   then
-    yieldLines $file | bin/rshell
-  elif [[ "$MODE" == "bash" ]]
-  then
-    yieldLines $file | bash -i
+    yieldLines $file | bash -i  # run bash in interactive mode
   else
-    yieldLines $file | $MODE
+    yieldLines $file | $COMMAND_SHELL
   fi
   # denote end of test execution
   echo # extra newline
